"use client";

import { useState, type CSSProperties } from "react";
import Image from "next/image";
import { KanbanSquare, RefreshCw, Workflow, X } from "lucide-react";
import { withBasePath } from "@/lib/paths";
import styles from "./StackSection.module.css";

type Cluster = "backend" | "data" | "delivery";

type Node = {
  cluster: Cluster;
  id: string;
  name: string;
  tier: "anchor" | "primary" | "secondary" | "support";
  position: [number, number];
  mobile: [number, number];
  detail: string;
};

// Coordinates are intentionally composed, rather than generated by a force layout.
const nodes: Node[] = [
  {
    id: "java",
    cluster: "backend",
    name: "Java",
    tier: "anchor",
    position: [465, 245],
    mobile: [180, 155],
    detail: "The foundation of my backend work.",
  },
  {
    id: "spring",
    cluster: "backend",
    name: "Spring Boot",
    tier: "primary",
    position: [285, 190],
    mobile: [83, 258],
    detail: "Application services, APIs and integrations.",
  },
  {
    id: "springsecurity",
    cluster: "backend",
    name: "Spring Security",
    tier: "secondary",
    position: [140, 110],
    mobile: [65, 65],
    detail: "Authentication and authorization for Spring applications.",
  },
  {
    id: "hibernate",
    cluster: "backend",
    name: "Hibernate",
    tier: "support",
    position: [460, 100],
    mobile: [285, 267],
    detail: "Object-relational persistence with PostgreSQL.",
  },
  {
    id: "junit",
    cluster: "backend",
    name: "JUnit",
    tier: "support",
    position: [355, 365],
    mobile: [291, 163],
    detail: "Automated tests for Java applications.",
  },
  {
    id: "maven",
    cluster: "backend",
    name: "Maven",
    tier: "support",
    position: [505, 410],
    mobile: [278, 65],
    detail: "Dependency management and repeatable Java builds.",
  },
  {
    id: "grpc",
    cluster: "backend",
    name: "gRPC",
    tier: "support",
    position: [100, 300],
    mobile: [65, 353],
    detail: "Typed service-to-service communication.",
  },
  {
    id: "websocket",
    cluster: "backend",
    name: "WebSocket",
    tier: "support",
    position: [205, 410],
    mobile: [204, 355],
    detail: "Persistent connections for real-time application updates.",
  },
  {
    id: "postgres",
    cluster: "data",
    name: "PostgreSQL",
    tier: "primary",
    position: [710, 155],
    mobile: [168, 150],
    detail: "Relational storage for application data.",
  },
  {
    id: "redis",
    cluster: "data",
    name: "Redis",
    tier: "secondary",
    position: [590, 65],
    mobile: [65, 65],
    detail: "Fast application caching and shared state.",
  },
  {
    id: "mongodb",
    cluster: "data",
    name: "MongoDB",
    tier: "support",
    position: [895, 70],
    mobile: [281, 65],
    detail: "Document storage through Spring Data.",
  },
  {
    id: "kafka",
    cluster: "data",
    name: "Kafka",
    tier: "secondary",
    position: [875, 220],
    mobile: [67, 255],
    detail: "Event streaming, with analytical ingestion into ClickHouse.",
  },
  {
    id: "rabbitmq",
    cluster: "data",
    name: "RabbitMQ",
    tier: "secondary",
    position: [645, 285],
    mobile: [285, 215],
    detail: "Asynchronous messaging between application services.",
  },
  {
    id: "clickhouse",
    cluster: "data",
    name: "ClickHouse",
    tier: "support",
    position: [1010, 145],
    mobile: [195, 323],
    detail: "Analytical queries over event data.",
  },
  {
    id: "docker",
    cluster: "delivery",
    name: "Docker",
    tier: "primary",
    position: [760, 400],
    mobile: [157, 145],
    detail: "Containerized applications, built and delivered through CI.",
  },
  {
    id: "kubernetes",
    cluster: "delivery",
    name: "Kubernetes",
    tier: "secondary",
    position: [930, 350],
    mobile: [280, 228],
    detail: "Orchestration and deployment of containerized services.",
  },
  {
    id: "githubactions",
    cluster: "delivery",
    name: "GitHub Actions",
    tier: "support",
    position: [595, 490],
    mobile: [70, 60],
    detail: "CI pipelines that build, test and package applications.",
  },
  {
    id: "nginx",
    cluster: "delivery",
    name: "Nginx",
    tier: "support",
    position: [1030, 440],
    mobile: [287, 65],
    detail: "Reverse proxy and ingress for deployed services.",
  },
  {
    id: "prometheus",
    cluster: "delivery",
    name: "Prometheus",
    tier: "support",
    position: [875, 500],
    mobile: [177, 305],
    detail: "Service and cluster metrics, visualized in Grafana.",
  },
  {
    id: "grafana",
    cluster: "delivery",
    name: "Grafana",
    tier: "support",
    position: [1030, 535],
    mobile: [64, 347],
    detail: "Dashboards for metrics collected by Prometheus.",
  },
];

// Each edge describes an integration or build/deployment relationship.
const edges = [
  ["java", "spring"],
  ["java", "maven"],
  ["java", "junit"],
  ["spring", "springsecurity"],
  ["spring", "hibernate"],
  ["hibernate", "postgres"],
  ["spring", "postgres"],
  ["spring", "redis"],
  ["spring", "mongodb"],
  ["spring", "kafka"],
  ["spring", "rabbitmq"],
  ["spring", "grpc"],
  ["spring", "websocket"],
  ["kafka", "clickhouse"],
  ["maven", "githubactions"],
  ["githubactions", "docker"],
  ["docker", "kubernetes"],
  ["kubernetes", "nginx"],
  ["kubernetes", "prometheus"],
  ["prometheus", "grafana"],
] as const;
const byId = Object.fromEntries(nodes.map((node) => [node.id, node]));
const clusters: { id: Cluster; label: string }[] = [
  { id: "backend", label: "Backend" },
  { id: "data", label: "Data & messaging" },
  { id: "delivery", label: "Delivery" },
];

const processes = [
  {
    name: "Scrum",
    description: "Спринты, ретроспективы, планирование",
    icon: RefreshCw,
  },
  { name: "Agile", description: "Итеративная разработка", icon: Workflow },
  { name: "Kanban", description: "Прозрачный поток задач", icon: KanbanSquare },
];

export default function StackSection() {
  const [selected, setSelected] = useState<string | null>(null);
  const [hovered, setHovered] = useState<string | null>(null);
  const [cluster, setCluster] = useState<Cluster>("backend");
  const active = hovered ?? selected;
  const connected = new Set<string>();
  if (active) {
    connected.add(active);
    for (const [from, to] of edges) {
      if (from === active) connected.add(to);
      if (to === active) connected.add(from);
    }
  }
  const mobilePosition = (node: Node): [number, number] =>
    cluster === "data" && node.id === "spring" ? [175, 55] : node.mobile;
  const visibleOnMobile = (node: Node) =>
    node.cluster === cluster || (cluster === "data" && node.id === "spring");

  return (
    <section
      id="stack"
      aria-labelledby="stack-title"
      className={`container ${styles.section}`}
      lang="en"
    >
      <header className={styles.heading}>
        <h2 id="stack-title">Technical Stack</h2>
      </header>

      <div className={styles.canvas}>
        <div className={styles.clusterNav} aria-label="Technology clusters">
          {clusters.map((item) => (
            <button
              key={item.id}
              type="button"
              aria-pressed={cluster === item.id}
              aria-controls="stack-map"
              onClick={() => {
                setCluster(item.id);
                setSelected(null);
                setHovered(null);
              }}
            >
              {item.label}
            </button>
          ))}
        </div>
        <div
          id="stack-map"
          className={styles.map}
          data-cluster={cluster}
          data-exploring={Boolean(active)}
          aria-label="Technology constellation"
        >
          {([false, true] as const).map((mobile) => (
            <svg
              key={String(mobile)}
              className={mobile ? styles.mobileLines : styles.desktopLines}
              viewBox={mobile ? "0 0 360 410" : "0 0 1100 590"}
              preserveAspectRatio="none"
              aria-hidden="true"
            >
              {edges.map(([from, to]) => {
                if (
                  mobile &&
                  (!visibleOnMobile(byId[from]) || !visibleOnMobile(byId[to]))
                )
                  return null;
                const source = mobile
                  ? mobilePosition(byId[from])
                  : byId[from].position;
                const target = mobile
                  ? mobilePosition(byId[to])
                  : byId[to].position;
                return (
                  <line
                    key={`${from}-${to}`}
                    x1={source[0]}
                    y1={source[1]}
                    x2={target[0]}
                    y2={target[1]}
                    className={
                      active === from || active === to
                        ? styles.activeLine
                        : undefined
                    }
                  />
                );
              })}
            </svg>
          ))}
          {nodes.map((node) => (
            <button
              key={node.id}
              type="button"
              className={`${styles.node} ${styles[node.tier]}`}
              data-cluster={node.cluster}
              data-active={active === node.id}
              data-connected={connected.has(node.id)}
              data-context={cluster === "data" && node.id === "spring"}
              style={
                {
                  "--x": `${node.position[0] / 11}%`,
                  "--y": `${node.position[1] / 5.9}%`,
                  "--mx": `${mobilePosition(node)[0] / 3.6}%`,
                  "--my": `${mobilePosition(node)[1] / 4.1}%`,
                } as CSSProperties
              }
              aria-label={node.name}
              aria-pressed={selected === node.id}
              aria-describedby={`stack-description-${node.id}`}
              onPointerEnter={(event) => {
                if (event.pointerType === "mouse") setHovered(node.id);
              }}
              onPointerLeave={() => setHovered(null)}
              onFocus={(event) => {
                if (event.currentTarget.matches(":focus-visible"))
                  setHovered(node.id);
              }}
              onBlur={() => setHovered(null)}
              onClick={() => {
                setHovered(null);
                setSelected((current) =>
                  current === node.id ? null : node.id,
                );
              }}
              onKeyDown={(event) => {
                if (event.key === "Escape") {
                  setSelected(null);
                  setHovered(null);
                }
              }}
            >
              <span className={styles.nodeDisc}>
                <Image
                  src={withBasePath(`/icons/constellation/${node.id}.svg`)}
                  alt=""
                  width={40}
                  height={40}
                  draggable={false}
                />
              </span>
              <span className={styles.nodeLabel}>{node.name}</span>
              <span id={`stack-description-${node.id}`} className="sr-only">
                {node.detail}
              </span>
              {node.id === "java" && (
                <span className={styles.coreLabel}>PRIMARY LANGUAGE</span>
              )}
            </button>
          ))}
        </div>
        <div className={styles.caption} id="stack-detail" hidden={!active}>
          {active && <span className={styles.captionDot} aria-hidden="true" />}
          <p aria-live="polite" aria-atomic="true">
            {active ? (
              <>
                <strong>{byId[active].name}</strong> — {byId[active].detail}
              </>
            ) : null}
          </p>
          {active ? (
            <button
              type="button"
              className={styles.clearSelection}
              aria-label="Clear technology selection"
              onClick={() => {
                setSelected(null);
                setHovered(null);
              }}
            >
              <X size={16} aria-hidden="true" />
            </button>
          ) : null}
        </div>
      </div>

      <div className={styles.supporting}>
        <section
          aria-labelledby="languages-title"
          className={styles.supportBlock}
        >
          <div className={styles.supportHeading}>
            <h3 id="languages-title">Languages</h3>
          </div>
          <div className={styles.languages}>
            {[
              { name: "Russian", code: "RU", level: "Native" },
              { name: "English", code: "EN", level: "B2" },
            ].map((language) => (
              <div key={language.code} className={styles.language}>
                <span className={styles.languageCode}>{language.code}</span>
                <span className={styles.languageName}>{language.name}</span>
                <span className={styles.proficiency}>{language.level}</span>
              </div>
            ))}
          </div>
        </section>
        <section
          aria-labelledby="processes-title"
          className={styles.supportBlock}
        >
          <div className={styles.supportHeading}>
            <h3 id="processes-title">Processes</h3>
          </div>
          <ul className={styles.processes}>
            {processes.map(({ name, description, icon: Icon }) => (
              <li key={name}>
                <Icon size={15} aria-hidden="true" />
                <span>{name}</span>
                <p lang="ru">{description}</p>
              </li>
            ))}
          </ul>
        </section>
      </div>
    </section>
  );
}
